{{- if eq .Values.architecture "master-replica" }}
# Redis Master ConfigMap
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "redis.fullname" . }}-master-config
  labels:
    {{- include "redis.labels" . | nindent 4 }}
    app.kubernetes.io/component: master
data:
  redis.conf: |
{{- if .Values.redis.master.config }}
{{ .Values.redis.master.config | indent 4 }}
{{- else }}
{{ .Values.redis.config | indent 4 }}
{{- end }}
{{- if .Values.redis.auth.enabled }}
    # Authentication
    requirepass ${REDIS_PASSWORD}
    masterauth ${REDIS_PASSWORD}
{{- end }}
---
# Redis Replica ConfigMap
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "redis.fullname" . }}-replica-config
  labels:
    {{- include "redis.labels" . | nindent 4 }}
    app.kubernetes.io/component: replica
data:
  redis.conf: |
{{- if .Values.redis.replica.config }}
{{ .Values.redis.replica.config | indent 4 }}
{{- else }}
{{ .Values.redis.config | indent 4 }}
{{- end }}
{{- if .Values.redis.auth.enabled }}
    # Authentication
    requirepass ${REDIS_PASSWORD}
    masterauth ${REDIS_PASSWORD}
{{- end }}
{{- else }}
# Standalone Redis ConfigMap
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "redis.fullname" . }}-config
  labels:
    {{- include "redis.labels" . | nindent 4 }}
data:
  redis.conf: |
{{ .Values.redis.config | indent 4 }}
{{- if .Values.redis.auth.enabled }}
    # Authentication
    requirepass ${REDIS_PASSWORD}
{{- end }}
{{- end }}