{{- if .Values.redisinsight.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "redis.fullname" . }}-redisinsight
  labels:
    {{- include "redis.labels" . | nindent 4 }}
    app.kubernetes.io/component: redisinsight
spec:
  replicas: {{ .Values.redisinsight.replicaCount }}
  selector:
    matchLabels:
      {{- include "redis.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: redisinsight
  template:
    metadata:
      {{- with .Values.redisinsight.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "redis.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/component: redisinsight
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "redis.serviceAccountName" . }}
      securityContext:
        fsGroup: 1000
      containers:
        - name: redisinsight
          image: "{{ .Values.redisinsight.image.repository }}:{{ .Values.redisinsight.image.tag }}"
          imagePullPolicy: {{ .Values.redisinsight.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 5540
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /healthcheck
              port: http
            initialDelaySeconds: 30
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /healthcheck
              port: http
            initialDelaySeconds: 10
            periodSeconds: 5
          resources:
            {{- toYaml .Values.redisinsight.resources | nindent 12 }}
          volumeMounts:
            - name: redisinsight-data
              mountPath: /data
          env:
            {{- if .Values.redis.auth.enabled }}
            - name: REDIS_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ include "redis.fullname" . }}-auth
                  key: redis-password
            {{- end }}
      volumes:
        {{- if .Values.redisinsight.persistence.enabled }}
        - name: redisinsight-data
          persistentVolumeClaim:
            claimName: {{ include "redis.fullname" . }}-redisinsight-data
        {{- else }}
        - name: redisinsight-data
          emptyDir: {}
        {{- end }}
      {{- with .Values.redisinsight.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.redisinsight.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.redisinsight.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
{{- end }}
