# WordPress configuration
wordpress:
  image:
    repository: wordpress
    tag: latest
    pullPolicy: IfNotPresent

  replicaCount: 1

  service:
    type: ClusterIP
    port: 80

  resources:
    limits:
      cpu: 500m
      memory: 512Mi
    requests:
      cpu: 250m
      memory: 256Mi

  persistence:
    enabled: true
    storageClass: ""
    accessMode: ReadWriteOnce
    size: 10Gi

  # WordPress environment variables
  env:
    tablePrefix: wp_

  # WordPress admin user (created on first deployment)
  admin:
    user: admin
    email: admin@example.com

  ingress:
    enabled: false
    className: ""
    annotations: {}
      # kubernetes.io/ingress.class: nginx
      # cert-manager.io/cluster-issuer: letsencrypt-prod
    hosts:
      - host: wordpress.local
        paths:
          - path: /
            pathType: Prefix
    tls: []
    #  - secretName: wordpress-tls
    #    hosts:
    #      - wordpress.local

# MariaDB configuration
mariadb:
  image:
    repository: mariadb
    tag: latest
    pullPolicy: IfNotPresent

  replicaCount: 1

  service:
    type: ClusterIP
    port: 3306

  resources:
    limits:
      cpu: 500m
      memory: 512Mi
    requests:
      cpu: 250m
      memory: 256Mi

  persistence:
    enabled: true
    storageClass: ""
    accessMode: ReadWriteOnce
    size: 8Gi

  # Database configuration
  database:
    name: wordpress
    user: wordpress

# Credentials
# Leave empty to auto-generate secure random passwords
secrets:
  mariadb:
    rootPassword: ""
    userPassword: ""
  wordpress:
    adminPassword: ""
