apiVersion: v1
kind: Secret
metadata:
  name: {{ include "mariadb.fullname" . }}
  labels:
    {{- include "mariadb.labels" . | nindent 4 }}
type: Opaque
data:
  mariadb-root-password: {{ include "mariadb.rootPassword" . | b64enc | quote }}
  {{- if .Values.auth.username }}
  mariadb-password: {{ include "mariadb.password" . | b64enc | quote }}
  {{- end }}
