apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "mariadb-galera-ha.recoveryConfigMapName" . }}
  labels:
    {{- include "mariadb-galera-ha.labels" . | nindent 4 }}
data:
  mode: "normal"
  bootstrapNode: ""
  bootstrapGeneration: "0"
  lastRecoveryTime: ""
