{{- if .Values.serviceAccount.create }}
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ include "mariadb-galera-ha.fullname" . }}
  labels:
    {{- include "mariadb-galera-ha.labels" . | nindent 4 }}
rules:
  - apiGroups: [""]
    resources: ["pods", "configmaps", "persistentvolumeclaims"]
    verbs: ["get", "list", "watch", "update", "patch"]
  - apiGroups: ["apps"]
    resources: ["statefulsets"]
    verbs: ["get", "list", "watch", "update", "patch"]
  - apiGroups: ["apps"]
    resources: ["statefulsets/scale"]
    verbs: ["update", "patch"]
  - apiGroups: ["batch"]
    resources: ["jobs"]
    verbs: ["get", "list", "watch", "create", "delete"]
{{- end }}
