{{- if not .Values.auth.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "mariadb-galera-ha.secretName" . }}
  labels:
    {{- include "mariadb-galera-ha.labels" . | nindent 4 }}
type: Opaque
data:
  mariadb-root-password: {{ include "mariadb-galera-ha.rootPassword" . | b64enc | quote }}
  mariadb-password: {{ include "mariadb-galera-ha.password" . | b64enc | quote }}
  mariadb-replication-password: {{ include "mariadb-galera-ha.replicationPassword" . | b64enc | quote }}
{{- end }}
