apiVersion: v2
name: redis
description: A Helm chart for Redis 8.2.2-alpine3.22
type: application
version: 0.1.0
appVersion: "8.2.2"
keywords:
  - redis
  - database
  - cache
home: https://redis.io
sources:
  - https://github.com/redis/redis
maintainers:
  - name: Redis Team
    email: support@redis.io