apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "wordpress.fullname" . }}-mariadb
  labels:
    app: {{ include "wordpress.name" . }}-mariadb
    chart: {{ include "wordpress.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  replicas: {{ .Values.mariadb.replicaCount }}
  selector:
    matchLabels:
      app: {{ include "wordpress.name" . }}-mariadb
      release: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: {{ include "wordpress.name" . }}-mariadb
        release: {{ .Release.Name }}
    spec:
      containers:
      - name: mariadb
        image: "{{ .Values.mariadb.image.repository }}:{{ .Values.mariadb.image.tag }}"
        imagePullPolicy: {{ .Values.mariadb.image.pullPolicy }}
        ports:
        - name: mysql
          containerPort: 3306
          protocol: TCP
        env:
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: {{ include "wordpress.fullname" . }}-secrets
              key: mariadb-root-password
        - name: MYSQL_DATABASE
          value: {{ .Values.mariadb.database.name | quote }}
        - name: MYSQL_USER
          value: {{ .Values.mariadb.database.user | quote }}
        - name: MYSQL_PASSWORD
          valueFrom:
            secretKeyRef:
              name: {{ include "wordpress.fullname" . }}-secrets
              key: mariadb-user-password
        volumeMounts:
        - name: mariadb-data
          mountPath: /var/lib/mysql
        resources:
          {{- toYaml .Values.mariadb.resources | nindent 10 }}
        livenessProbe:
          exec:
            command:
            - sh
            - -c
            - "mysqladmin ping -u root -p${MYSQL_ROOT_PASSWORD}"
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 5
        readinessProbe:
          exec:
            command:
            - sh
            - -c
            - "mysqladmin ping -u root -p${MYSQL_ROOT_PASSWORD}"
          initialDelaySeconds: 5
          periodSeconds: 5
          timeoutSeconds: 1
      volumes:
      - name: mariadb-data
        {{- if .Values.mariadb.persistence.enabled }}
        persistentVolumeClaim:
          claimName: {{ include "wordpress.fullname" . }}-mariadb-pvc
        {{- else }}
        emptyDir: {}
        {{- end }}
