apiVersion: v1
kind: Service
metadata:
  name: {{ include "wordpress.fullname" . }}-mariadb
  labels:
    app: {{ include "wordpress.name" . }}-mariadb
    chart: {{ include "wordpress.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  type: {{ .Values.mariadb.service.type }}
  ports:
  - port: {{ .Values.mariadb.service.port }}
    targetPort: mysql
    protocol: TCP
    name: mysql
  selector:
    app: {{ include "wordpress.name" . }}-mariadb
    release: {{ .Release.Name }}
