{{- if .Values.wordpress.ingress.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "wordpress.fullname" . }}
  labels:
    app: {{ include "wordpress.name" . }}
    chart: {{ include "wordpress.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
  {{- with .Values.wordpress.ingress.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  {{- if .Values.wordpress.ingress.className }}
  ingressClassName: {{ .Values.wordpress.ingress.className }}
  {{- end }}
  {{- if .Values.wordpress.ingress.tls }}
  tls:
    {{- range .Values.wordpress.ingress.tls }}
    - hosts:
        {{- range .hosts }}
        - {{ . | quote }}
        {{- end }}
      secretName: {{ .secretName }}
    {{- end }}
  {{- end }}
  rules:
    {{- range .Values.wordpress.ingress.hosts }}
    - host: {{ .host | quote }}
      http:
        paths:
          {{- range .paths }}
          - path: {{ .path }}
            pathType: {{ .pathType }}
            backend:
              service:
                name: {{ include "wordpress.fullname" $ }}
                port:
                  number: {{ $.Values.wordpress.service.port }}
          {{- end }}
    {{- end }}
{{- end }}
