name: Build and Publish Helm Charts

on:
  push:
    branches:
      - main

jobs:
  build:
    name: Build Helm Charts
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Helm
        run: |
          curl -fsSL -o get_helm.sh https://raw.githubusercontent.com/helm/helm/main/scripts/get-helm-3
          chmod +x get_helm.sh
          ./get_helm.sh

      - name: Package Helm charts
        run: |
          mkdir -p packaged-charts
          for chart in charts/*; do
            if [ -d "$chart" ]; then
              helm package "$chart" --destination packaged-charts
            fi
          done

      - name: Upload artifacts for GitHub Pages
        uses: actions/upload-pages-artifact@v2
        with:
          path: packaged-charts

  deploy:
    name: Deploy to GitHub Pages
    needs: build
    runs-on: ubuntu-latest

    permissions:
      pages: write
      id-token: write

    steps:
      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v2
