name: Lint and Test Charts

on:
  pull_request:
    paths:
      - 'charts/**'
      - '.ct.yaml'

jobs:
  lint-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Helm
        uses: azure/setup-helm@v4
        with:
          version: v3.14.4

      - name: Run chart-testing (lint)
        uses: helm/chart-testing-action@v2.6.1
        with:
          command: lint
          config: .ct.yaml

      # Optional e2e (requires a Kubernetes cluster)
      # - name: Create kind cluster
      #   uses: helm/kind-action@v1
      # - name: Run chart-testing (install)
      #   uses: helm/chart-testing-action@v2.6.1
      #   with:
      #     command: install
      #     config: .ct.yaml
